name: Alerta Hola Mundo

on:
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Ejecutar programa Hola Mundo
        run: node hola.js

      - name: Enviar notificación a ntfy
        run: |
          curl -X POST https://ntfy.sh/devops-itla \
          -H "Title: GitHub Actions" \
          -H "Priority: high" \
          -d "Se hizo push a la rama main y se ejecutó Hola Mundo"
