name: Alerta CI - Hola Mundo

on:
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar mensaje Hola Mundo
        run: echo "Hola Mundo desde GitHub Actions 🚀"

      - name: Enviar notificación a ntfy
        run: |
          curl -X POST \
          -H "Title: 🚀 Push a main" \
          -H "Priority: 3" \
          -d "Se subió código al repositorio practica1-github correctamente." \
          https://ntfy.sh/devops-itla
